#!/bin/sh
set -eux
sudo yum install -y \
	gcc-c++ \
	gzip \
	libutempter-devel \
	make \
	ncurses-devel \
	openssl-devel \
	protobuf-compiler \
	protobuf-devel \
	tar \
	zlib-devel
wget https://mosh.org/mosh-1.3.2.tar.gz
tar xaf mosh-1.3.2.tar.gz
cd mosh-1.3.2
./configure
make
sudo make install
